### ISSUE TITLE
can we upload .zip file in slicer 

### ISSUE THREAD

**Issue by kmordhwaj** [jzeyl/3D-Slicer-Scripts#1]
Hi @jzeyl 
First of all its great work.
I want to know is there any posiible way through which we can upload a .zip file of a folder which contains over 100 nifti files in the slicer through script?
Thanks in advance.

**Comment by jzeyl** [comment]
Hello kmordhwaj,
If the folder is unzipped you could use one of the following

Open file from command line:https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#open-a-file-with-slicer-at-the-command-line
Load volume from the python interpreter:  https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#load-volume-from-file

This forum is probably your best choice for more specific questions:  https://discourse.slicer.org/
